package hr.fer.oprpp1.hw04.db;

/**
 * Student record class.
 */
public class StudentRecord {

    private String jmbag;
    private String lastName;
    private String firstName;
    private int finalGrade;

    /**
     * Creates a new StudentRecord.
     * 
     * @param jmbag      student's jmbag
     * @param lastName   student's last name
     * @param firstName  student's first name
     * @param finalGrade student's final grade
     */
    public StudentRecord(String jmbag, String lastName, String firstName, int finalGrade) {
        this.jmbag = jmbag;
        this.lastName = lastName;
        this.firstName = firstName;
        this.finalGrade = finalGrade;
    }

    /**
     * Autogenerated hashCode method.
     * 
     * 
     * @return int
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((jmbag == null) ? 0 : jmbag.hashCode());
        result = prime * result + ((lastName == null) ? 0 : lastName.hashCode());
        result = prime * result + ((firstName == null) ? 0 : firstName.hashCode());
        result = prime * result + finalGrade;
        return result;
    }

    /**
     * Autogenerated equals method.
     * 
     * @param obj
     * @return boolean
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        StudentRecord other = (StudentRecord) obj;
        if (jmbag == null) {
            if (other.jmbag != null)
                return false;
        } else if (!jmbag.equals(other.jmbag))
            return false;
        if (lastName == null) {
            if (other.lastName != null)
                return false;
        } else if (!lastName.equals(other.lastName))
            return false;
        if (firstName == null) {
            if (other.firstName != null)
                return false;
        } else if (!firstName.equals(other.firstName))
            return false;
        if (finalGrade != other.finalGrade)
            return false;
        return true;
    }

    /**
     * Returns student's jmbag.
     * 
     * @return String
     */
    public String getJmbag() {
        return jmbag;
    }

    /**
     * Returns student's last name.
     * 
     * @return String
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Returns student's first name.
     * 
     * @return String
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Returns student's final grade.
     * 
     * @return int
     */
    public int getFinalGrade() {
        return finalGrade;
    }

}
